export type Project = {
  id: string;
  title: string;
  place: string;
  theme: string;
  summary: string;
  sourceFolder: string;
  archiveName: string;
  size: string;
  files: string[];
  formats: string[];
  qgisProjects: string[];
  highlights: string[];
};

export const projects: Project[] = [
  {
    id: 'heritage-development',
    title: 'Balancing Heritage and Development',
    place: 'Liverpool',
    theme: 'Heritage planning',
    summary: 'A layered planning project comparing conservation assets, transit corridors, green space, landmarks, building heights, and development constraints.',
    sourceFolder: '01_GIS_for_Balancing_Heritage_and_Development',
    archiveName: '01_GIS_for_Balancing_Heritage_and_Development.zip',
    size: '210 MB',
    files: ['QGIS project', 'Shapefiles', 'Attachments'],
    formats: ['QGS', 'SHP', 'ZIP'],
    qgisProjects: ['1. GIS for balancing heritage and development STUDENTS.qgs', '0. Data/1. GIS for balancing heritage and development STUDENTS.qgs'],
    highlights: ['Conservation areas', 'Former World Heritage Site buffers', 'Transit catchments', 'Local plan layers'],
  },
  {
    id: 'qgis-basics',
    title: 'QGIS Basics',
    place: 'Spain, Washington DC, United Kingdom',
    theme: 'Foundational mapping',
    summary: 'Introductory QGIS exercises covering urban areas, Spanish cities, local context heights, the DC Metro, and UK greenbelt mapping.',
    sourceFolder: '02_Module_2_QGIS_Basics',
    archiveName: '02_Module_2_QGIS_Basics.zip',
    size: '827 MB',
    files: ['QGIS projects', 'GeoPackages', 'Shapefiles', 'Archives'],
    formats: ['QGS', 'QGZ', 'GPKG', 'SHP', 'CSV', 'ZIP'],
    qgisProjects: ['QGIS Basics (students).qgs', 'Dc metro.qgz', 'UK Green.qgz'],
    highlights: ['Urban area layers', 'Hospitals and schools', 'Autonomous communities', 'Transit basemaps'],
  },
  {
    id: 'attribute-tables',
    title: 'Attribute Tables and Feature Creation',
    place: 'United States, London, Lisbon',
    theme: 'Data editing',
    summary: 'A module focused on attribute inspection, creating layers, editing features, and joining tabular thinking to spatial layers.',
    sourceFolder: '03_Module_3_Attribute_Table_Create_Layers',
    archiveName: '03_Module_3_Attribute_Table_Create_Layers.zip',
    size: '110 MB',
    files: ['QGIS project', 'GeoPackages', 'Shapefiles'],
    formats: ['QGS', 'GPKG', 'SHP'],
    qgisProjects: ['1. Attribute table + Create layers and features.qgs'],
    highlights: ['States and cities', 'CO2 grid emissions', 'Urban evolution layer', 'Created layers'],
  },
  {
    id: 'geometry-geoprocessing',
    title: 'Geometry and Geoprocessing',
    place: 'New York City',
    theme: 'Spatial operations',
    summary: 'A New York-oriented exercise set using buffers, centroids, clipped layers, residential/commercial differences, zoning, subway stations, and building footprints.',
    sourceFolder: '04_Module_3_Geometry_and_Geoprocessing',
    archiveName: '04_Module_3_Geometry_and_Geoprocessing.zip',
    size: '1.4 GB',
    files: ['QGIS project', 'GeoPackages', 'Shapefiles', 'Zips'],
    formats: ['QGS', 'GPKG', 'SHP', 'ZIP'],
    qgisProjects: ['2. Geometry and geoprocessing tools.qgs'],
    highlights: ['Buffer analysis', 'Clipped outputs', 'Subway access layers', 'Manhattan buildings'],
  },
  {
    id: 'basic-styling',
    title: 'Basic Layer Styling',
    place: 'Brazil and regional datasets',
    theme: 'Cartographic styling',
    summary: 'A cartography and styling module with demographic density, roads, businesses, indigenous land, planned railways, and federative units.',
    sourceFolder: '05_Module_3_Basic_Layer_Styling',
    archiveName: '05_Module_3_Basic_Layer_Styling.zip',
    size: '635 MB',
    files: ['QGIS project', 'GeoPackages', 'Shapefiles', 'Zips'],
    formats: ['QGS', 'GPKG', 'SHP', 'ZIP'],
    qgisProjects: ['3. Basic layer styling.qgs'],
    highlights: ['Population density', 'Road networks', 'Indigenous land', 'Railway styling'],
  },
  {
    id: 'spatial-analysis',
    title: 'Spatial Analysis Tools',
    place: 'San Francisco and New York',
    theme: 'Accessibility analysis',
    summary: 'A spatial-analysis project with public transport routes, bike-network buffers, building permits, zoning, intersections, and residential access layers.',
    sourceFolder: '06_Module_4_Spatial_Analysis_Tools',
    archiveName: '06_Module_4_Spatial_Analysis_Tools.zip',
    size: '1.1 GB',
    files: ['QGIS project', 'GeoPackages', 'CSV', 'Transit archives'],
    formats: ['QGS', 'GPKG', 'SHP', 'CSV', 'ZIP'],
    qgisProjects: ['1. Spatial analysis tools.qgs'],
    highlights: ['Transit buffers', 'Bike network accessibility', 'Building permits', 'Zoning overlays'],
  },
  {
    id: 'advanced-styling',
    title: 'Advanced Layer Styling',
    place: 'Madrid, Manhattan, Canary Islands',
    theme: 'Advanced cartography',
    summary: 'A visual styling module using building heights, land use, administrative layers, transport buffers, and sampled building footprints.',
    sourceFolder: '07_Module_4_Advanced_Layer_Styling',
    archiveName: '07_Module_4_Advanced_Layer_Styling.zip',
    size: '1.4 GB',
    files: ['QGIS project', 'GeoPackages', 'Shapefiles', 'Zips'],
    formats: ['QGS', 'GPKG', 'SHP', 'ZIP'],
    qgisProjects: ['2. Advanced layer styling.qgs'],
    highlights: ['Madrid boundaries', 'Building height surfaces', 'Land-use styling', 'Urban area layers'],
  },
  {
    id: 'link-tables',
    title: 'Link Tables, Field Calculator, Map Exports',
    place: 'Sydney and Australia',
    theme: 'Census data workflows',
    summary: 'A large census-focused module linking tables, deriving fields, preparing density outputs, and exporting map products from Australian statistical areas.',
    sourceFolder: '08_Module_5_Link_Tables_Field_Calculator_Map_Exports',
    archiveName: '08_Module_5_Link_Tables_Field_Calculator_Map_Exports.zip',
    size: '3.4 GB',
    files: ['QGIS project', 'GeoPackages', 'Census CSVs', 'Metadata', 'Archives'],
    formats: ['QGS', 'GPKG', 'CSV', 'XLSX', 'ZIP'],
    qgisProjects: ['1. Link tables + Field calculator + AI-aided wf + Map exports.qgs'],
    highlights: ['SA1 census data', 'Density calculations', 'National roads', 'Map export workflow'],
  },
  {
    id: 'essential-plugins',
    title: 'Essential Plugins',
    place: 'Madrid',
    theme: 'Plugin-assisted workflows',
    summary: 'A compact module exploring geolocation, isochrones, directions, shopping-mall access, and permit data through QGIS plugin workflows.',
    sourceFolder: '09_Module_5_Essential_Plugins',
    archiveName: '09_Module_5_Essential_Plugins.zip',
    size: '3.4 MB',
    files: ['QGIS project', 'GeoPackages', 'CSV', 'Excel'],
    formats: ['QGS', 'GPKG', 'CSV', 'XLSX', 'SHP'],
    qgisProjects: ['2. Essential plugins.qgs'],
    highlights: ['Isochrones', 'Geocoded permits', 'Directions', 'Neighborhood context'],
  },
  {
    id: 'project-one-mapity',
    title: 'Project 1: Mapity',
    place: 'Manhattan',
    theme: 'Urban suitability',
    summary: 'A project package combining Manhattan neighborhoods, bus stops, metro-meter outputs, DSM data, residential selections, and two QGIS project files.',
    sourceFolder: '10_Project_1_Mapity_Module_3',
    archiveName: '10_Project_1_Mapity_Module_3.zip',
    size: '151 MB',
    files: ['QGIS projects', 'GeoPackages'],
    formats: ['QGZ', 'GPKG'],
    qgisProjects: ['Mapity.qgz', 'Module 3.qgz'],
    highlights: ['Manhattan neighborhoods', 'Transit proximity', 'Residential permit selection', 'DSM layer'],
  },
  {
    id: 'dmv-line-extension',
    title: 'DMV Line Extension',
    place: 'Washington DC region',
    theme: 'Transit extension proposal',
    summary: 'A transit proposal package with proposed extension layers, Purple Line alignment and station files, bus stops, metro lines, employment hubs, and a map PDF.',
    sourceFolder: '11_DMV_Line_Extension',
    archiveName: '11_DMV_Line_Extension.zip',
    size: '63 MB',
    files: ['GeoPackages', 'Shapefiles', 'Excel', 'PDF'],
    formats: ['GPKG', 'SHP', 'XLSX', 'PDF', 'ZIP'],
    qgisProjects: [],
    highlights: ['Purple Line alignment', 'Proposed extension', 'Employment hubs', 'Station access'],
  },
  {
    id: 'miami-flood-risk',
    title: 'Miami-Dade Flood Risk Analysis',
    place: 'Miami-Dade County',
    theme: 'Flood exposure',
    summary: 'A flood-risk analysis pairing FEMA flood zones with population block data and summary outputs for exposure visualization.',
    sourceFolder: '12_Miami_Dade_Flood_Risk_Analysis',
    archiveName: '12_Miami_Dade_Flood_Risk_Analysis.zip',
    size: '59 MB',
    files: ['QGIS project', 'Shapefiles', 'GeoPackage', 'CSV', 'Images'],
    formats: ['QGZ', 'SHP', 'GPKG', 'CSV', 'PNG'],
    qgisProjects: ['Excercise Module 5.qgz'],
    highlights: ['FEMA flood zones', 'NHGIS population blocks', 'Population risk summary', 'Flood-zone visualization'],
  },
  {
    id: 'qgis-final',
    title: 'QGIS Final',
    place: 'New York, London, Barranco',
    theme: 'Final mapping exercises',
    summary: 'A final-project collection with crash data, parks, boundaries, London wards, proposed park shapefiles, and multiple compact QGIS projects.',
    sourceFolder: '13_QGIS_Final',
    archiveName: '13_QGIS_Final.zip',
    size: '30 MB',
    files: ['QGIS projects', 'GeoPackages', 'Shapefiles', 'CSV'],
    formats: ['QGZ', 'GPKG', 'SHP', 'CSV'],
    qgisProjects: ['ex1.qgz', 'g.qgz'],
    highlights: ['Motor vehicle crashes', 'Park proposal layer', 'London wards', 'NYC boundaries'],
  },
  {
    id: 'qa-three',
    title: 'Q&A 3 Workshop',
    place: 'Urban analysis exercise',
    theme: 'Workshop dataset',
    summary: 'A dated workshop package collecting transit buffers, building footprints and heights, residential areas, cities, and screenshot references.',
    sourceFolder: '14_QA_3_2026-02-17',
    archiveName: '14_QA_3_2026-02-17.zip',
    size: '470 MB',
    files: ['QGIS project', 'GeoPackages', 'Shapefiles', 'Images'],
    formats: ['QGZ', 'GPKG', 'SHP', 'PNG'],
    qgisProjects: ['20260218_Q&A 3.qgz'],
    highlights: ['Building heights', 'Transit buffers', 'Residential areas', 'Urban screenshots'],
  },
  {
    id: 'loose-gis-files',
    title: 'Loose GIS Files',
    place: 'Standalone',
    theme: 'Unsorted extras',
    summary: 'Two small standalone GIS files that did not clearly belong to a larger project folder but were worth preserving with the portfolio.',
    sourceFolder: '15_Loose_GIS_Files',
    archiveName: '15_Loose_GIS_Files.zip',
    size: '108 KB',
    files: ['QGIS project', 'GeoPackage'],
    formats: ['QGZ', 'GPKG'],
    qgisProjects: ['Mapity.qgz'],
    highlights: ['Standalone Mapity project', 'Test GeoPackage'],
  },
];
