export type Project = {
  id: string;
  title: string;
  place: string;
  theme: string;
  summary: string;
  sourceFolder: string;
  archiveName: string | string[];
  size: string;
  files: string[];
  formats: string[];
  qgisProjects: string[];
  highlights: string[];
  preview?: {
    image: string;
    title: string;
    caption: string;
  };
};

export const projects: Project[] = [
  {
        id: 'dmv-line-extension',
        title: 'DMV Transit Extension and Employment Access',
        place: 'Washington DC region',
        theme: 'Transit extension proposal',
        summary: 'A transit proposal connecting extension geometry, Purple Line alignment and station files, bus stops, metro lines, employment hubs, and a map export.',
        sourceFolder: '11_DMV_Line_Extension',
        archiveName: '11_DMV_Line_Extension.zip',
        size: '63 MB',
        files: ['GeoPackages', 'Shapefiles', 'Excel', 'PDF'],
        formats: ['GPKG', 'SHP', 'XLSX', 'PDF', 'ZIP'],
        qgisProjects: [],
        highlights: ['Purple Line alignment', 'Proposed extension', 'Employment hubs', 'Station access'],
        preview: {
          image: '/project-previews/dmv-proposed-extension-map.jpg',
          title: 'DMV Employment Access and Proposed Extension',
          caption: 'Employment hubs, proposed extension, metro lines, Purple Line stations, and existing metro stops.',
        },
      },
  {
        id: 'madrid-building-heights',
        title: 'Madrid Building Height Visualization',
        place: 'Madrid',
        theme: 'Urban morphology',
        summary: 'A building-height visualization mapping Madrid city structure with height classes, city boundary context, and a dark basemap composition.',
        sourceFolder: '16_Madrid_Building_Height_Visualization',
        archiveName: '16_Madrid_Building_Height_Visualization.zip',
        size: '205 MB',
        files: ['Map export', 'GeoPackage', 'Print layout'],
        formats: ['PDF', 'GPKG', 'QPT'],
        qgisProjects: [],
        highlights: ['Building height classes', 'Madrid city boundary', 'Dark basemap styling', 'Print layout export'],
        preview: {
          image: '/project-previews/madrid-building-height-visualization.jpg',
          title: 'Madrid Building Height Visualization',
          caption: 'Madrid building heights in graduated purple classes over a dark basemap, with city boundary and legend.',
        },
      },
  {
        id: 'advanced-styling',
        title: 'Madrid 3D Urban Form Styling',
        place: 'Madrid',
        theme: '3D GIS visualization',
        summary: 'A 3D GIS styling study using extruded building geometry, aerial imagery, and urban form context around central Madrid.',
        sourceFolder: '07_Module_4_Advanced_Layer_Styling',
        archiveName: '07_Module_4_Advanced_Layer_Styling.zip',
        size: '1.4 GB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles', 'Map screenshot'],
        formats: ['QGS', 'GPKG', 'SHP', 'PNG', 'ZIP'],
        qgisProjects: ['2. Advanced layer styling.qgs'],
        highlights: ['3D building extrusion', 'Aerial basemap context', 'Urban form styling', 'Madrid building layers'],
        preview: {
          image: '/project-previews/advanced-3d-gis-styling.jpg',
          title: 'Madrid 3D Urban Form Styling',
          caption: '3D GIS styling view of Madrid building geometry over aerial imagery, emphasizing urban form and height variation.',
        },
      },
  {
        id: 'miami-flood-risk',
        title: 'Miami-Dade Flood Exposure and Population Risk',
        place: 'Miami-Dade County',
        theme: 'Flood exposure',
        summary: 'A flood-exposure analysis pairing FEMA flood zones with population block data and summary outputs for risk visualization.',
        sourceFolder: '12_Miami_Dade_Flood_Risk_Analysis',
        archiveName: '12_Miami_Dade_Flood_Risk_Analysis.zip',
        size: '59 MB',
        files: ['Project layers', 'Shapefiles', 'GeoPackage', 'CSV', 'Map export'],
        formats: ['QGZ', 'SHP', 'GPKG', 'CSV', 'PNG'],
        qgisProjects: ['Excercise Module 5.qgz'],
        highlights: ['FEMA flood zones', 'NHGIS population blocks', 'Population risk summary', 'Flood-zone visualization'],
        preview: {
          image: '/project-previews/miami-flood-zones.jpg',
          title: 'Flood Zones Graduated by Population Risk',
          caption: 'Miami-Dade flood exposure with a population risk legend and graduated blue risk classes.',
        },
      },
  {
        id: 'project-one-mapity',
        title: 'Manhattan Transit-Oriented Suitability Study',
        place: 'Manhattan',
        theme: 'Urban suitability',
        summary: 'A Manhattan suitability study combining neighborhoods, bus stops, transit-distance outputs, DSM data, and residential selections.',
        sourceFolder: '10_Project_1_Mapity_Module_3',
        archiveName: '10_Project_1_Mapity_Module_3.zip',
        size: '151 MB',
        files: ['Project layers', 'GeoPackages'],
        formats: ['QGZ', 'GPKG'],
        qgisProjects: ['Mapity.qgz', 'Module 3.qgz'],
        highlights: ['Manhattan neighborhoods', 'Transit proximity', 'Residential permit selection', 'DSM layer'],
      },
  {
        id: 'spatial-analysis',
        title: 'Transit Accessibility and Urban Development Analysis',
        place: 'San Francisco and New York',
        theme: 'Accessibility analysis',
        summary: 'An accessibility analysis combining public transport routes, bike-network buffers, building permits, zoning, intersections, and residential access layers.',
        sourceFolder: '06_Module_4_Spatial_Analysis_Tools',
        archiveName: '06_Module_4_Spatial_Analysis_Tools.zip',
        size: '1.1 GB',
        files: ['Project layers', 'GeoPackages', 'CSV', 'Transit data'],
        formats: ['QGS', 'GPKG', 'SHP', 'CSV', 'ZIP'],
        qgisProjects: ['1. Spatial analysis tools.qgs'],
        highlights: ['Transit buffers', 'Bike network accessibility', 'Building permits', 'Zoning overlays'],
      },
  {
        id: 'heritage-development',
        title: 'Heritage and Growth Suitability Analysis',
        place: 'Liverpool',
        theme: 'Heritage planning',
        summary: 'A planning analysis comparing conservation assets, transit corridors, green space, landmarks, building heights, and development constraints.',
        sourceFolder: '01_GIS_for_Balancing_Heritage_and_Development',
        archiveName: '01_GIS_for_Balancing_Heritage_and_Development.zip',
        size: '210 MB',
        files: ['Project layers', 'Shapefiles', 'Reference data'],
        formats: ['QGS', 'SHP', 'ZIP'],
        qgisProjects: ['1. GIS for balancing heritage and development STUDENTS.qgs', '0. Data/1. GIS for balancing heritage and development STUDENTS.qgs'],
        highlights: ['Conservation areas', 'Former World Heritage Site buffers', 'Transit catchments', 'Local plan layers'],
      },
  {
        id: 'link-tables',
        title: 'Australian Census Linkage and Density Mapping',
        place: 'Sydney and Australia',
        theme: 'Census geography',
        summary: 'Census geography analysis linking tabular data, deriving density fields, and preparing map outputs from Australian statistical areas.',
        sourceFolder: '08_Module_5_Link_Tables_Field_Calculator_Map_Exports',
        archiveName: [
          '08_Module_5_Link_Tables_Field_Calculator_Map_Exports_part-1-source-datapack.zip',
          '08_Module_5_Link_Tables_Field_Calculator_Map_Exports_part-2-project-layers.zip',
        ],
        size: '3.4 GB',
        files: ['Project layers', 'GeoPackages', 'Census CSVs', 'Metadata'],
        formats: ['QGS', 'GPKG', 'CSV', 'XLSX', 'ZIP'],
        qgisProjects: ['1. Link tables + Field calculator + AI-aided wf + Map exports.qgs'],
        highlights: ['SA1 census data', 'Density calculations', 'National roads', 'Map export workflow'],
      },
  {
        id: 'essential-plugins',
        title: 'Madrid Isochrone and Geocoding Analysis',
        place: 'Madrid',
        theme: 'Location intelligence',
        summary: 'Location-intelligence analysis using geolocation, isochrones, directions, shopping-mall access, and permit data.',
        sourceFolder: '09_Module_5_Essential_Plugins',
        archiveName: '09_Module_5_Essential_Plugins.zip',
        size: '3.4 MB',
        files: ['Project layers', 'GeoPackages', 'CSV', 'Excel'],
        formats: ['QGS', 'GPKG', 'CSV', 'XLSX', 'SHP'],
        qgisProjects: ['2. Essential plugins.qgs'],
        highlights: ['Isochrones', 'Geocoded permits', 'Directions', 'Neighborhood context'],
      },
  {
        id: 'geometry-geoprocessing',
        title: 'NYC Geoprocessing and Access Analysis',
        place: 'New York City',
        theme: 'Spatial operations',
        summary: 'A New York-oriented spatial analysis using buffers, centroids, clipped layers, residential/commercial differences, zoning, subway stations, and building footprints.',
        sourceFolder: '04_Module_3_Geometry_and_Geoprocessing',
        archiveName: '04_Module_3_Geometry_and_Geoprocessing.zip',
        size: '1.4 GB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles'],
        formats: ['QGS', 'GPKG', 'SHP', 'ZIP'],
        qgisProjects: ['2. Geometry and geoprocessing tools.qgs'],
        highlights: ['Buffer analysis', 'Clipped outputs', 'Subway access layers', 'Manhattan buildings'],
      },
  {
        id: 'qgis-final',
        title: 'Urban Safety, Parks, and Boundary Mapping',
        place: 'New York, London, Barranco',
        theme: 'Urban mapping',
        summary: 'Urban mapping with crash data, parks, boundaries, London wards, and proposed park layers.',
        sourceFolder: '13_QGIS_Final',
        archiveName: '13_QGIS_Final.zip',
        size: '30 MB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles', 'CSV'],
        formats: ['QGZ', 'GPKG', 'SHP', 'CSV'],
        qgisProjects: ['ex1.qgz', 'g.qgz'],
        highlights: ['Motor vehicle crashes', 'Park proposal layer', 'London wards', 'NYC boundaries'],
      },
  {
        id: 'basic-styling',
        title: 'Thematic Cartography and Demographic Styling',
        place: 'Brazil and regional datasets',
        theme: 'Cartographic styling',
        summary: 'Thematic cartography using demographic density, roads, businesses, indigenous land, planned railways, and federative units.',
        sourceFolder: '05_Module_3_Basic_Layer_Styling',
        archiveName: '05_Module_3_Basic_Layer_Styling.zip',
        size: '635 MB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles'],
        formats: ['QGS', 'GPKG', 'SHP', 'ZIP'],
        qgisProjects: ['3. Basic layer styling.qgs'],
        highlights: ['Population density', 'Road networks', 'Indigenous land', 'Railway styling'],
      },
  {
        id: 'qgis-basics',
        title: 'Urban Context and Transit Basemap Series',
        place: 'Spain, Washington DC, United Kingdom',
        theme: 'Regional basemap development',
        summary: 'A multi-region basemap series covering urban areas, Spanish cities, local context heights, the DC Metro, and UK greenbelt mapping.',
        sourceFolder: '02_Module_2_QGIS_Basics',
        archiveName: '02_Module_2_QGIS_Basics.zip',
        size: '827 MB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles', 'Reference data'],
        formats: ['QGS', 'QGZ', 'GPKG', 'SHP', 'CSV', 'ZIP'],
        qgisProjects: ['QGIS Basics (students).qgs', 'Dc metro.qgz', 'UK Green.qgz'],
        highlights: ['Urban area layers', 'Hospitals and schools', 'Autonomous communities', 'Transit basemaps'],
      },
  {
        id: 'attribute-tables',
        title: 'Spatial Data Editing and Attribute Design',
        place: 'United States, London, Lisbon',
        theme: 'Data editing',
        summary: 'Spatial data design focused on attribute structure, feature creation, layer editing, and clean geospatial datasets.',
        sourceFolder: '03_Module_3_Attribute_Table_Create_Layers',
        archiveName: '03_Module_3_Attribute_Table_Create_Layers.zip',
        size: '110 MB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles'],
        formats: ['QGS', 'GPKG', 'SHP'],
        qgisProjects: ['1. Attribute table + Create layers and features.qgs'],
        highlights: ['States and cities', 'CO2 grid emissions', 'Urban evolution layer', 'Created layers'],
      },
  {
        id: 'urban-form-reference',
        title: 'Urban Form Reference Layers',
        place: 'Urban analysis',
        theme: 'Urban morphology',
        summary: 'Reference layers for transit buffers, building footprints and heights, residential areas, cities, and map imagery.',
        sourceFolder: '14_QA_3_2026-02-17',
        archiveName: '14_QA_3_2026-02-17.zip',
        size: '470 MB',
        files: ['Project layers', 'GeoPackages', 'Shapefiles', 'Map imagery'],
        formats: ['QGZ', 'GPKG', 'SHP', 'PNG'],
        qgisProjects: ['20260218_Q&A 3.qgz'],
        highlights: ['Building heights', 'Transit buffers', 'Residential areas', 'Urban screenshots'],
      },
  {
        id: 'loose-gis-files',
        title: 'Supplemental Spatial Layers',
        place: 'Standalone',
        theme: 'Supplemental files',
        summary: 'Standalone spatial layers preserved as supporting portfolio material.',
        sourceFolder: '15_Loose_GIS_Files',
        archiveName: '15_Loose_GIS_Files.zip',
        size: '108 KB',
        files: ['Project layer', 'GeoPackage'],
        formats: ['QGZ', 'GPKG'],
        qgisProjects: ['Mapity.qgz'],
        highlights: ['Standalone Mapity project', 'Test GeoPackage'],
      },
  {
        id: 'uk-park-count',
        title: 'UK Park Count Data Assembly',
        place: 'United Kingdom',
        theme: 'Data acquisition and aggregation',
        summary: 'A supporting study focused on gathering greenspace data, joining it to county geography, and producing county-level park counts.',
        sourceFolder: '17_UK_Park_Count_Data_Assembly',
        archiveName: '17_UK_Park_Count_Data_Assembly.zip',
        size: '389 MB',
        files: ['Map export', 'Greenspace shapefile', 'Reference data'],
        formats: ['PDF', 'SHP'],
        qgisProjects: [],
        highlights: ['Greenspace source data', 'County-level aggregation', 'Park count labels', 'Data gathering and preparation'],
        preview: {
          image: '/project-previews/uk-park-count-data-assembly.jpg',
          title: 'UK Park Count Data Assembly',
          caption: 'Included as a data-gathering example: greenspace records were collected, joined to county geography, and aggregated into park counts.',
        },
      },
];
